HAI 1.2
    I HAS A LAST ITZ 1
    I HAS A LASTER ITZ 2
    I HAS A LASTEST
    I HAS A EVENPOWA ITZ 2
    IM IN YR CLASS
        LASTEST R SUM OF LAST AN LASTER
        BOTH SAEM LASTEST BIGGR OF LASTEST AN 4000000, O RLY?
            YA RLY, GTFO
        OIC
        BOTH SAEM MOD OF LASTEST AN 2 AN 0, O RLY?
            YA RLY, EVENPOWA R SUM OF EVENPOWA LASTEST
        OIC
        LAST R LASTER
        LASTER R LASTEST
    IM OUTTA YR CLASS
    VISIBLE EVENPOWA
KTHXBYE
