HAI 1.2
    BTW THIZ IS MY FIRSTZ LOLCODE PROGRAM!!!!!!
    I HAS A SUM ITZ 0
    IM IN YR MOM UPPIN YR N TIL BOTH SAEM N AN 1000
        EITHER OF BOTH SAEM MOD OF N AN 3 AN 0 AN BOTH SAEM MOD OF N AN 5 AN 0
        O RLY?
        YA RLY
            SUM R SUM OF SUM AN N
        OIC
    IM OUTTA YR MOM
    VISIBLE SUM
KTHXBYE