HAI 1.2
    I HAS A LIMIT ITZ 100
    I HAS A SUMOFSQUARES ITZ 0
    I HAS A SQUAREOFSUMS ITZ 0
    IM IN YR LIFE UPPIN YR N WILE DIFFRINT N SUM OF LIMIT 1
        SUMOFSQUARES R SUM OF SUMOFSQUARES PRODUKT OF N N
        SQUAREOFSUMS R SUM OF SQUAREOFSUMS N
    IM OUTTA YR LIFE
    SQUAREOFSUMS R PRODUKT OF SQUAREOFSUMS SQUAREOFSUMS
    VISIBLE DIFF OF SQUAREOFSUMS SUMOFSQUARES
KTHXBYE
